### ISSUE TITLE
`consult-gh-repo-list` results in error: consult-gh--async-repo-list: Wrong type argument: sequencep, 35

### ISSUE THREAD

**Issue by Duy-X** [armindarvish/consult-gh#196]
**Describe the bug**
Unable to run `consult-gh-repo-list` (error: consult-gh--async-repo-list: Wrong type argument: sequencep, 35)

**To Reproduce**
1. Use the following config (**NOTE:** I use `elpaca`):
```elisp
(use-package consult-gh
  :after consult)
```
2. Invoke `consult-gh-repo-list` with `M-x`
3. I get this error (with `toggle-debug-on-error` turned on)
```elisp
Debugger entered--Lisp error: (wrong-type-argument sequencep 35)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_291>(nil)
  consult-gh--async-repo-list("Enter Org Name:  " consult-gh--repo-list-builder nil)
  consult-gh-repo-list()
  funcall-interactively(consult-gh-repo-list)
  command-execute(consult-gh-repo-list record)
  execute-extended-command(nil "consult-gh-repo-list" nil)
  funcall-interactively(execute-extended-command nil "consult-gh-repo-list" nil)
  command-execute(execute-extended-command)
```

**Expected behavior**
According to the repo, I should be able to "[find] repositories for a given GitHub user/organization, similar to running gh repo list in the command line."

**Important Information:**
 - OS: MacOS
 - Version of Emacs 30 (via `emacs-plus`)
 - Version of `gh`:  2.65.0 (2025-01-06)
 - Version of `consult`: 1.9
 - The installation method and the configuration you are using with your consult-gh: using `elpaca` and the above config
 - Confirmed I have this error with `emacs -Q`.
 
**Additional context**
Same / similar error message for other `consult-gh-*` commands as well.

**Comment by iwahbe** [comment]
I am getting the same error, on a very similar setup (MacOS, emacs@30 from emacs-plus, consult 1.9 installed with elpaca).

**Comment by armindarvish** [comment]
@Duy-X and @iwahbe I am guessing that the problem is because I just pushed some breaking changes yesterday to make consult-gh compatible with the latest consult API changes. As a result
the latest version of conslt-gh is incompatible with consult 1.9 stable release anymore. 

So, either you have to update your consult to the latest consult HEAD, or use the stable consult-gh here: https://github.com/armindarvish/consult-gh/releases or install from MELPA Stable.

Can you double-check and let me know if that solves the problem?

**Comment by magthe** [comment]
I see the same issue here. Given that the straight recipe still points to consult 1.9 it's a bit of a chore to move to consult 1.10. Is there a tag in consult-gh I can use for now? Maybe `v2.2`?

**Comment by armindarvish** [comment]
@magthe Yes, v2.2 is the stable release to use, and this commit should work: [1e5f0c4
](https://github.com/armindarvish/consult-gh/commit/1e5f0c4f18d30f82b20d5bffbec31a9bf32b03ae)

**Comment by armindarvish** [comment]
@Duy-X, @iwahbe, and @magthe, There was actually another issue that was causing that specific problem. You may already be on the latest consult anyway. So please check again and see if you still have the problem.

**Comment by magthe** [comment]
I'm now on these commits, and I still see the same behaviour.

| pkg        | commit SHA | branch |
|------------|------------|--------|
| consult    | 31b5c19    | main   |
| consult-gh | afb5ed7    | main   |

**Comment by armindarvish** [comment]
@magthe Sorry for the confusion, seems that in the last commit I missed to actually tangle the org file. I just pushed again and tested it and the issue is fixed. Please let me know if you still see some issues.  

If you are installing from MELPA, it should be fixed in a few hours when it updates to the latest, otherwise just pull the latest consult-gh. Commit: b021164

**Comment by Duy-X** [comment]
@armindarvish Using elpaca, I am now unable to install the package:

<img width="865" alt="Image" src="https://github.com/user-attachments/assets/2618d559-8aba-4441-8328-f85aaefd829d" />

Not sure why I get this error now? As you can see I am on consult 1.9.

**Comment by ardar848** [comment]
@Duy-X Oh man, we are going in circle here. Sorry for the confusion. I updated the requirement in consult-gh's head so it requires the latest consult (the one that does work with latest consult-gh) and that's why you are seeing that issue. 

So if you are using consult 1.9, you have to use consult-gh v2.2 in elpaca. Alternatively, use the latest version of both consult and consult-gh.

**Comment by armindarvish** [comment]
@Duy-X Oh man, we are going in circle here. Sorry for the confusion. I updated the requirement in consult-gh's head so it requires the latest consult (the one that does work with latest consult-gh) and that's why you are seeing that issue.  

So if you are using consult 1.9, you have to use consult-gh v2.2 in elpaca. Alternatively, use the latest version of both consult and consult-gh.

**Comment by armindarvish** [comment]
I'm closing this now as I don't see any new activities here. Feel free to reopen if the issue persists.
